### ISSUE TITLE
rustsec.org is down

### ISSUE THREAD

**Issue by nothingismagick** [RustSec/rustsec.github.io#10]
```
$ ping rustsec.org
ping: cannot resolve rustsec.org: Unknown host
```

![Screen Shot 2019-12-11 at 10 51 58](https://user-images.githubusercontent.com/35242872/70610686-4a498300-1c04-11ea-87c6-6bb7bff56eef.png)

**Comment by tarcieri** [comment]
It's a DNS issue. See also https://github.com/RustSec/advisory-db/issues/206
