### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by iulianR** [RustSec/rustsec.github.io#12]
Hi, each time a visit an advisory on the site, it takes me a few seconds of scanning the page to see "where's what".
I am no visual designer, but maybe you should consider increasing the font-weight for headings to 700 (bold), instead the current one (300).

Here are some screenshots for comparison:
![Screenshot from 2020-05-13 10-59-20](https://user-images.githubusercontent.com/6775259/81786837-dd1a8080-9508-11ea-9021-1db18730daad.png)
![Screenshot from 2020-05-13 10-59-10](https://user-images.githubusercontent.com/6775259/81786809-d55adc00-9508-11ea-9241-bfcfce1461cc.png)

Thanks!

**Comment by tarcieri** [comment]
I can try increasing it a little

**Comment by tarcieri** [comment]
I made the headers slightly bolder in 0a1f5d64
