### ISSUE TITLE
Please update the website with new advisories

### ISSUE THREAD

**Issue by jonasbb** [RustSec/rustsec.github.io#17]
Sorry for the noise here, but could you please update the website with the new advisories?
I got a message about RUSTSEC-2020-0095, which is not available on the website.

It seems the website is missing `RUSTSEC-2020-0094`, `RUSTSEC-2020-0095`, `RUSTSEC-2021-0001`, and `RUSTSEC-2021-0002`, which also includes the mdbook vulnerability.

The commit to this repository seem manually. Maybe the website should automatically be updated whenever the advisory-db changes/gets updates.

**Comment by tarcieri** [comment]
Done.

Yes, it's manual. Yes, it'd be amazing if it were automated. Would you like to volunteer to work on that?

**Comment by jonasbb** [comment]
Thank you. Would it be acceptable to add Github Actions to the advisory-db repository and this repository and allow the Action on this repository to create commits. Then I might give it a shot. This will probably still require a bit of help to get all the secrets setup.

A simpler solution would be to run a cron script every x hours and regenerate the website in every case.

**Comment by tarcieri** [comment]
Yes, it'd be nice if there were something like the [`assign-ids` workflow](https://github.com/RustSec/advisory-db/blob/master/.github/workflows/assign-ids.yml) which automatically filed pull requests, either to https://github.com/RustSec/rustsec.github.io or potentially migrating to a `gh-pages` branch of this repo if that's more convenient.

**Comment by jonasbb** [comment]
Currently, I cannot even build the website. Neither the cargo command nor the bundle/jekyll steps work.
https://github.com/jonasbb/rustsec.github.io/runs/1663880038?check_suite_focus=true#step:4:64

**Comment by tarcieri** [comment]
Strange. As it were all Jekyll rendering is managed via GitHub Pages right now, so you don't need to worry about that. It just needs to install and run `rustsec-admin web` to regenerate the Markdown files.

(Separately I'd love to get off Jekyll and have `rustsec-admin web` output HTML files directly but that's more work I don't have time to do)

**Comment by tarcieri** [comment]
Tried adding a basic automation here: https://github.com/RustSec/rustsec.github.io/pull/18
